---
# tasks file for roles/python-pydata

- name: system packages | install epel repo
  become: true
  yum:
    name: epel-release
    state: present

- name: system packages | install python data analysis tools
  become: true
  yum:
    name:
      - numpy
      - python-ipython
      - python-matplotlib
      - python-numexpr
      - python-pandas
      - python-tables
      - python2-scikit-image
      - scipy
      - PyYAML
    state: present
